server:
  port: 8980
spring:
  application:
    name: API-ADMINS
  cloud:
    nacos:
      server-addr: 192.168.20.137:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.20.137:3306/zzFree?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  redis:
    host: 192.168.20.137
    port: 6379

mybatis:
  mapper-locations: classpath:zzfree/mapper/*.xml
  type-aliases-package: zzfree.entity
logging:
  level:
    zzfree.dao: debug