server:
  port: 8981
spring:
  application:
    name: API-CATEGORIES
  cloud:
    nacos:
      server-addr: 192.168.20.137:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.20.137:3306/zzFree?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

mybatis:
    mapper-locations: classpath:zzfree/mapper/*.xml
    type-aliases-package: zzfree.entity
logging:
    level:
      zzfree.dao: debug